### ISSUE TITLE
CSR read/write exception handling is not aligned with spec

### ISSUE THREAD

**Issue by howard0su** [PulseRain/Reindeer#10]
Based on my understanding to the spec, we should ignore the unknown CSR registers access and generate illegal instruction trap when trying to write to the readonly CSR registers.

current implementation generate a storage page trap which is not align with the spec, also generate trap for any known CSRs read or write access.

some interesting discussions here:
https://groups.google.com/a/groups.riscv.org/forum/#!msg/sw-dev/Xu6UmcIAKIk/WvQufntnAAAJ

**Comment by PulseRainmaker** [comment]
Here is what I've found in the latest spec:

**Attempts to access a non-existent CSR raise an illegal instruction exception. Attempts to access a
CSR without appropriate privilege level or to write a read-only register also raise illegal instruction
exceptions. A read/write register might also contain some bits that are read-only, in which case
writes to the read-only bits are ignored.**

Looks like we need to change the current exception type (page fault) to the type for illegal instructions, but we should not ignore the unknown CSR registers access.
